#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Ferroelectric polarization from the generalized spin-current model.

    P_GSC = sum_{<ij>_n} M^n_ij (S_i x S_j)

where M^n_ij is a 3x3 matrix attached to the bond joining the nth neighbours i
and j. Only the matrix of one reference bond per shell is an independent
quantity -- the one lying along x, obtained by four-state mapping -- and every
other bond in the shell follows from the point group.

Two things fix how that propagation has to be written, and both are easy to get
wrong in a way that survives every test but flips the answer's sign.

Covariance
----------
P is a polar vector, while S_i x S_j is the cross product of two axial vectors
and is therefore axial. Demanding that P = M C hold in every frame gives

    M(R d) = det(R) R M(d) R^T,

and the det(R) is not optional: it is invisible on the three proper rotations
and changes the sign on the six improper ones. A useful consequence is that the
bond antisymmetry needs no separate rule. Inversion has R = -I and det = -1, so
the law already returns M(-d) = -M(d), matching S_i x S_j = -(S_j x S_i). The
orbit is therefore generated by the group action alone.

Setting
-------
NiI2 is P-3m1 (#164), not P-31m (#162): the twofold axes lie along the a axes,
at 0, 60 and 120 degrees, so all six first neighbours sit on a twofold axis and
the reference bond's stabiliser is {E, C2x}. That is what forces the reference
matrix into the five-parameter shape

    [[A, 0, 0], [0, B, C], [0, D, E]],

and the published matrices have exactly that shape, which is an independent
confirmation of the setting -- in the #162 setting x would lie in a mirror
instead and M[0][0] would be forced to zero. `_selftest` asserts the stabiliser
condition, so a lattice rotated by 30 degrees relative to the matrices is
reported rather than silently mis-transformed.

The 60 degree trap
------------------
The three positive first-neighbour directions are a1 (0 deg), a1 + a2 (60 deg)
and a2 (120 deg), but 60 degrees is *not* in the C3 orbit of x: R_z(60) is not
an element of D3d, being R_z(240) times a twofold rotation about z. The 60
degree matrix has to be reached as -M(240 deg). Substituting 60 degrees into
R_z(t) M R_z(t)^T directly gives the wrong sign on M[0][2] and M[2][0] only,
which no symmetry check on the proper rotations alone would catch.

Third neighbours share the first neighbours' directions at twice the distance,
so they reuse this machinery with their own reference matrix. Second neighbours
do not: they point at 30, 90 and 150 degrees, lie in a mirror rather than on a
twofold axis, and their matrix has the complementary shape (zero diagonal, four
free parameters). They are a separate four-state mapping and are deliberately
absent here rather than wrongly generated from M^1.

Run this file directly to execute the self-test; run it on a dump to write the
P(t) time series.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import NamedTuple

import numpy as np

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))
sys.path.insert(0, str(_HERE.parent))

from geometry import lammps_box_to_lattice, reciprocal_lattice_from_real  # noqa: E402
from lattice_grid import (  # noqa: E402
    grid_from_cfg,
    lattice_from_frame as _lattice_from_frame,
    layer_grids,
)


# ----------------------------------------------------------------------
# The measured input
# ----------------------------------------------------------------------
# Reference matrices for the bond along +x, in units of M_UNIT. Shape is
# [[A, 0, 0], [0, B, C], [0, D, E]]; the zeros are imposed by C2x and are
# asserted, not assumed.
M_REFERENCE: dict[int, np.ndarray] = {
    1: np.array([[11.0, 0.0, 0.0],
                 [0.0, 109.0, 139.0],
                 [0.0, -4.0, 5.0]]),
    3: np.array([[-1.0, 0.0, 0.0],
                 [0.0, 16.0, 164.0],
                 [0.0, -12.0, -10.0]]),
}

#: The matrices above are quoted in 1e-5 e Angstrom.
M_UNIT = 1.0e-5

#: Index step along a lattice vector that reaches each neighbour shell. First
#: neighbours are one cell away, third neighbours two, in the same directions.
SHELL_STEP: dict[int, int] = {1: 1, 3: 2}

#: (p, q) means the neighbour at cell (i + p, j + q), i.e. direction p a1 + q a2.
_FAMILY_OFFSETS = ((1, 0), (0, 1), (1, 1))

DEFAULT_SHELLS = (1, 3)

#: 1 e Angstrom in C m, for the areal conversion.
_E_ANGSTROM_IN_C_M = 1.602176634e-19 * 1.0e-10


# ----------------------------------------------------------------------
# Symmetry
# ----------------------------------------------------------------------
def rotation_z(degrees: float) -> np.ndarray:
    t = np.radians(degrees)
    c, s = np.cos(t), np.sin(t)
    return np.array([[c, -s, 0.0], [s, c, 0.0], [0.0, 0.0, 1.0]])


C2X = np.diag([1.0, -1.0, -1.0])
INVERSION = -np.eye(3)


def d3d_operations() -> list[np.ndarray]:
    """The twelve operations of -3m, as C3^k . C2x^b . i^c."""
    identity = np.eye(3)
    return [
        rotation_z(120.0 * k) @ (C2X if b else identity) @ (INVERSION if c else identity)
        for k in range(3)
        for b in (0, 1)
        for c in (0, 1)
    ]


def transform(rotation: np.ndarray, matrix: np.ndarray) -> np.ndarray:
    """M -> det(R) R M R^T, the transformation law of the axial-to-polar tensor."""
    return float(np.linalg.det(rotation)) * rotation @ matrix @ rotation.T


def _angle_of(direction: np.ndarray) -> float:
    """In-plane direction angle in degrees, wrapped to [0, 360)."""
    angle = np.degrees(np.arctan2(direction[1], direction[0])) % 360.0
    return float(angle % 360.0)


def direction_matrices(reference: np.ndarray) -> dict[int, np.ndarray]:
    """{angle in degrees: M} over the orbit of the reference bond along +x.

    Built by acting with the whole group, so the det(R) factor, the stabiliser
    and the bond antisymmetry are all exercised here rather than assumed. An
    operation that maps the reference bond onto one already visited must
    reproduce the same matrix; if it does not, the reference matrix is not
    invariant under its own stabiliser and the frame convention is wrong.
    """
    reference = np.asarray(reference, dtype=float)
    orbit: dict[int, np.ndarray] = {}
    for rotation in d3d_operations():
        direction = rotation @ np.array([1.0, 0.0, 0.0])
        key = int(round(_angle_of(direction))) % 360
        candidate = transform(rotation, reference)
        seen = orbit.get(key)
        if seen is not None and not np.allclose(seen, candidate, atol=1e-9):
            raise ValueError(
                "The reference matrix is not invariant under the stabiliser of its own "
                "bond, so it cannot belong to a D3d-symmetric bond along x. In the "
                "P-3m1 setting used by NiI2 the x axis is a twofold axis, which forces "
                "M[0][1] = M[0][2] = M[1][0] = M[2][0] = 0. Check that a1 is along x "
                "and that the matrix is not quoted in the P-31m setting, which is "
                "rotated by 30 degrees."
            )
        orbit[key] = candidate
    return orbit


def _matrix_for_direction(orbit: dict[int, np.ndarray], direction: np.ndarray,
                          tol_deg: float = 1e-3) -> np.ndarray:
    """The orbit member pointing along `direction`.

    Looked up by the bond's actual Cartesian angle rather than by which lattice
    vector produced it, so a box whose a1 is not along x still gets the right
    matrix -- and a box misaligned with the reference frame raises instead of
    silently using the wrong one.
    """
    angle = _angle_of(direction)
    for key, matrix in orbit.items():
        if min(abs(angle - key), 360.0 - abs(angle - key)) < tol_deg:
            return matrix
    raise ValueError(
        f"Bond direction at {angle:.4f} degrees is not in the D3d orbit of the "
        f"reference bond, whose members are at {sorted(orbit)} degrees. The lattice is "
        "rotated relative to the M matrices -- a 30 degree offset means the matrices "
        "are quoted in the other setting of -3m (P-31m rather than P-3m1)."
    )


# ----------------------------------------------------------------------
# Bonds
# ----------------------------------------------------------------------
class BondFamily(NamedTuple):
    """One set of parallel bonds: every site paired with the same neighbour."""

    shell: int
    offset: tuple[int, int]
    angle: float
    site_i: np.ndarray
    site_j: np.ndarray
    matrix: np.ndarray


def _families_one_layer(
    site_of: np.ndarray,
    n1: int,
    n2: int,
    lattice: np.ndarray,
    shells: tuple[int, ...],
    orbits: dict[int, dict[int, np.ndarray]],
) -> list[BondFamily]:
    # The offsets below count primitive cells, so the bond direction has to be
    # built from the primitive vectors. Taking the box vectors instead is right
    # only when n1 == n2 and silently skews every direction otherwise.
    a1, a2 = lattice[0] / n1, lattice[1] / n2

    families: list[BondFamily] = []
    for shell in shells:
        step = SHELL_STEP[shell]
        if min(n1, n2) <= 2 * step:
            raise ValueError(
                f"A {n1} x {n2} grid is too small for neighbour shell {shell}: the bond "
                f"reaches {step} cell(s) away, so under the periodic wrap it coincides "
                "with its own reverse and would be counted twice. Use a supercell with "
                f"more than {2 * step} cells along both axes, or drop this shell."
            )
        for p, q in _FAMILY_OFFSETS:
            offset = (p * step, q * step)
            direction = offset[0] * a1 + offset[1] * a2
            neighbour = np.roll(site_of, (-offset[0], -offset[1]), axis=(0, 1))
            families.append(BondFamily(
                shell=shell,
                offset=offset,
                angle=_angle_of(direction),
                site_i=site_of.ravel(),
                site_j=neighbour.ravel(),
                matrix=_matrix_for_direction(orbits[shell], direction),
            ))
    return families


def build_families(
    x: np.ndarray,
    y: np.ndarray,
    z: np.ndarray,
    lattice: np.ndarray,
    *,
    shells: tuple[int, ...] = DEFAULT_SHELLS,
    single_layer: bool = True,
    grid: tuple[int, int] | None = None,
    reference: dict[int, np.ndarray] | None = None,
) -> list[list[BondFamily]]:
    """Bond families per layer, each unordered bond appearing exactly once.

    Only the three positive directions of each shell are generated. The other
    three are their reverses, and taking a bond twice with M(-d) = -M(d) and
    S_j x S_i = -(S_i x S_j) would simply double the answer.
    """
    reference = reference or M_REFERENCE
    unknown = sorted(set(shells) - set(SHELL_STEP))
    if unknown:
        raise ValueError(
            f"No neighbour-shell geometry for shell(s) {unknown}. Shells 1 and 3 share "
            "the twofold-axis directions and are generated here; shell 2 points along "
            "the mirrors instead and needs its own four-state mapping, with a matrix of "
            "a different shape."
        )
    missing = sorted(set(shells) - set(reference))
    if missing:
        raise ValueError(f"No reference M matrix supplied for shell(s) {missing}.")

    orbits = {shell: direction_matrices(reference[shell]) for shell in shells}
    positions = np.stack([np.asarray(x, float), np.asarray(y, float), np.asarray(z, float)],
                         axis=1)
    lattice = np.asarray(lattice, dtype=float)

    per_layer: list[list[BondFamily]] = []
    for where, site_of, n1, n2 in layer_grids(positions, lattice, single_layer, grid):
        local = _families_one_layer(site_of, n1, n2, lattice, tuple(shells), orbits)
        per_layer.append([
            family._replace(site_i=where[family.site_i], site_j=where[family.site_j])
            for family in local
        ])
    return per_layer


# ----------------------------------------------------------------------
# The polarization itself
# ----------------------------------------------------------------------
def _unit(vectors: np.ndarray) -> np.ndarray:
    norm = np.linalg.norm(vectors, axis=1, keepdims=True)
    if np.any(norm == 0.0):
        raise ValueError(
            "Some sites carry a zero spin, which has no direction. Drop them with "
            "--drop-zero-vector, or select the magnetic sublattice with --element."
        )
    return vectors / norm


def family_polarization(m: np.ndarray, family: BondFamily) -> np.ndarray:
    """Per-bond contribution M (S_i x S_j) of one family, shape (n_bonds, 3)."""
    chirality = np.cross(m[family.site_i], m[family.site_j])
    return chirality @ family.matrix.T


def layer_polarization(
    m: np.ndarray,
    families_per_layer: list[list[BondFamily]],
    *,
    spin_length: float = 1.0,
) -> np.ndarray:
    """Total P of each layer, shape (n_layers, 3), in e Angstrom.

    Summed over bonds before the matrix product would be equivalent; it is done
    the other way round so that this shares its arithmetic exactly with
    `site_polarization` and the two cannot disagree.
    """
    scale = M_UNIT * spin_length ** 2
    return np.array([
        scale * sum(family_polarization(m, family).sum(axis=0) for family in families)
        for families in families_per_layer
    ])


def site_polarization(
    m: np.ndarray,
    families_per_layer: list[list[BondFamily]],
    n_sites: int,
    *,
    spin_length: float = 1.0,
) -> np.ndarray:
    """Per-site p_i, shape (n_sites, 3), in e Angstrom, with sum_i p_i = P.

    Each bond's contribution is split equally between its two ends, which is
    the same convention topocharge.py uses to spread a triangle's charge over
    its vertices, and for the same reason: tripcolor wants a value per vertex.
    """
    out = np.zeros((n_sites, 3), dtype=float)
    for families in families_per_layer:
        for family in families:
            half = 0.5 * family_polarization(m, family)
            np.add.at(out, family.site_i, half)
            np.add.at(out, family.site_j, half)
    return M_UNIT * spin_length ** 2 * out


def areal_pC_per_m(polarization: np.ndarray, lattice: np.ndarray) -> np.ndarray:
    """P summed over the whole box, in e Angstrom -> areal polarization in pC/m.

    A monolayer has no thickness to divide by, so the honest reduction of a
    two-dimensional dipole density is per unit area of sheet, giving C/m rather
    than the C/m^2 of a bulk ferroelectric. The area is the box's, so for a
    bilayer this is the polarization of the stack, not of one layer.
    """
    lattice = np.asarray(lattice, dtype=float)
    box_area = abs(np.cross(lattice[0][:2], lattice[1][:2]))              # Angstrom^2
    return np.asarray(polarization) * _E_ANGSTROM_IN_C_M / (box_area * 1.0e-20) * 1.0e12


# ----------------------------------------------------------------------
# Frame interface
# ----------------------------------------------------------------------
_FAMILY_CACHE: dict[tuple, list[list[BondFamily]]] = {}


def families_for_frame(frame: dict, cfg: dict | None = None) -> list[list[BondFamily]]:
    """Bond families for one frame, built once and reused.

    The connectivity is cached on the grid shape, so the atom order has to be
    the same in every frame -- LAMMPS guarantees that with
    `dump_modify <id> sort id`.
    """
    cfg = cfg or {}
    lattice = _lattice_from_frame(frame)
    single_layer = bool(cfg.get("single_layer", True))
    grid = grid_from_cfg(cfg)
    shells = tuple(cfg.get("shells") or DEFAULT_SHELLS)
    n_sites = int(frame["x"].size)

    key = (n_sites, single_layer, tuple(grid) if grid else None, shells,
           np.round(lattice, 6).tobytes())
    families = _FAMILY_CACHE.get(key)
    if families is None:
        families = build_families(
            frame["x"], frame["y"], frame["z"], lattice,
            shells=shells, single_layer=single_layer, grid=grid,
        )
        _FAMILY_CACHE[key] = families
    return families


def _spins(frame: dict) -> np.ndarray:
    if "u" not in frame:
        raise ValueError(
            "The polarization needs the spin direction, so --vector is required, e.g. "
            "--vector 'c_outsp[1]' 'c_outsp[2]' 'c_outsp[3]'."
        )
    return _unit(np.stack([frame["u"], frame["v"], frame["w"]], axis=1).astype(float))


def frame_polarization(frame: dict, cfg: dict | None = None) -> np.ndarray:
    """Total P of one frame, shape (n_layers, 3), in e Angstrom."""
    cfg = cfg or {}
    return layer_polarization(
        _spins(frame), families_for_frame(frame, cfg),
        spin_length=float(cfg.get("spin_length", 1.0)),
    )


def frame_site_polarization(frame: dict, cfg: dict | None = None) -> np.ndarray:
    """Per-site p_i of one frame, shape (n_sites, 3), in e Angstrom."""
    cfg = cfg or {}
    return site_polarization(
        _spins(frame), families_for_frame(frame, cfg), int(frame["x"].size),
        spin_length=float(cfg.get("spin_length", 1.0)),
    )


_COMPONENTS = {"x": 0, "y": 1, "z": 2}


def site_density(frame: dict, cfg: dict | None = None, component: str = "norm") -> np.ndarray:
    """One scalar per site for --color px/py/pz/pnorm."""
    p = frame_site_polarization(frame, cfg)
    if component == "norm":
        return np.linalg.norm(p, axis=1)
    return p[:, _COMPONENTS[component]]


__all__ = [
    "BondFamily",
    "DEFAULT_SHELLS",
    "M_REFERENCE",
    "M_UNIT",
    "areal_pC_per_m",
    "build_families",
    "d3d_operations",
    "direction_matrices",
    "families_for_frame",
    "frame_polarization",
    "frame_site_polarization",
    "layer_polarization",
    "rotation_z",
    "site_density",
    "site_polarization",
    "transform",
]


# ----------------------------------------------------------------------
# Command line: the P(t) time series
# ----------------------------------------------------------------------
def _iter_frames(dump_path: Path, *, vector, element, drop_zero_vector,
                 frame_start, frame_stop, frame_step):
    """Frames one at a time, so a long trajectory never sits in memory at once."""
    from dumpframe import extract, read_one_frame

    scanned = 0
    with Path(dump_path).open() as fh:
        while True:
            if frame_stop is not None and scanned >= frame_stop:
                return
            record = read_one_frame(fh)
            if record is None:
                return
            timestep, box_header, box_lines, columns, atom_lines = record
            if scanned >= frame_start and (scanned - frame_start) % frame_step == 0:
                frame = extract(columns, atom_lines, vector=vector, element=element,
                                drop_zero_vector=drop_zero_vector)
                frame["frame_index"] = scanned
                frame["timestep"] = timestep
                frame["box_header"] = box_header
                frame["box_lines"] = box_lines
                yield frame
            scanned += 1


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="polarization.py",
        description="Write the spin-current polarization P(t) of a dump trajectory.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("input_dump", type=Path, help="Input LAMMPS dump file")
    parser.add_argument("--vector", nargs=3, required=True, metavar=("SX", "SY", "SZ"),
                        help="The three spin columns, e.g. "
                             "--vector 'c_outsp[1]' 'c_outsp[2]' 'c_outsp[3]'")
    parser.add_argument("--element", type=str, default="all",
                        help="Element symbol to include, or 'all'. The sites must be one "
                             "per primitive cell, so a dump holding the iodines too needs "
                             "--element Ni")
    parser.add_argument("--drop-zero-vector", action="store_true",
                        help="Skip atoms whose spin is exactly zero")
    parser.add_argument("--single-layer", action="store_true",
                        help="Treat the frame as one layer instead of splitting at the "
                             "z midpoint into two independently bonded layers")
    parser.add_argument("--shells", type=int, nargs="+", default=list(DEFAULT_SHELLS),
                        metavar="N", help="Neighbour shells to sum over")
    parser.add_argument("--spin-length", type=float, default=1.0, metavar="S",
                        help="Spin length S. P scales as S^2; the reference matrices were "
                             "fitted for the convention this has to match")
    parser.add_argument("--lattice-grid", "--topo-grid", type=int, nargs=2,
                        dest="lattice_grid", metavar=("N1", "N2"), default=None,
                        help="Cell repeats, read off the positions when omitted")
    parser.add_argument("--frame-start", type=int, default=0, help="First frame to read")
    parser.add_argument("--frame-stop", type=int, default=None, help="Stop before this frame")
    parser.add_argument("--frame-step", type=int, default=1, help="Read every nth frame")
    parser.add_argument("--out", type=Path, default=Path("polarization.dat"),
                        help="Output table")
    return parser


def main(argv=None) -> None:
    args = build_parser().parse_args(argv)
    cfg = {
        "single_layer": args.single_layer,
        "shells": tuple(args.shells),
        "spin_length": args.spin_length,
        "lattice_grid": tuple(args.lattice_grid) if args.lattice_grid else None,
    }

    rows: list[tuple] = []
    lattice = None
    n_sites = n_layers = 0
    for frame in _iter_frames(
        args.input_dump, vector=tuple(args.vector), element=args.element,
        drop_zero_vector=args.drop_zero_vector, frame_start=args.frame_start,
        frame_stop=args.frame_stop, frame_step=args.frame_step,
    ):
        per_layer = frame_polarization(frame, cfg)
        if lattice is None:
            lattice = _lattice_from_frame(frame)
            n_sites = int(frame["x"].size)
            n_layers = per_layer.shape[0]
            print(f"[INFO] {n_sites} site(s), {n_layers} layer(s), shells {args.shells}, "
                  f"S = {args.spin_length}")
        rows.append((frame["frame_index"], frame["timestep"],
                     per_layer.sum(axis=0), per_layer))

    if not rows:
        raise SystemExit("No frames were read; check --frame-start/--frame-stop.")

    header = ["frame", "timestep", "Px", "Py", "Pz"]
    if n_layers > 1:
        header += [f"P{c}_L{n + 1}" for n in range(n_layers) for c in "xyz"]
    with args.out.open("w") as fh:
        fh.write(f"# {' '.join(sys.argv)}\n")
        fh.write(f"# sites {n_sites}  layers {n_layers}  shells {tuple(args.shells)}  "
                 f"S {args.spin_length}\n")
        fh.write("# P is the box total in e Angstrom; divide by the site count for the "
                 "value per formula unit\n")
        fh.write("# " + "  ".join(f"{name:>14s}" for name in header)[2:] + "\n")
        for index, timestep, total, per_layer in rows:
            values = [f"{index:>14d}", f"{int(timestep):>14d}"]
            values += [f"{v:>14.6e}" for v in total]
            if n_layers > 1:
                values += [f"{v:>14.6e}" for v in per_layer.ravel()]
            fh.write("  ".join(values) + "\n")

    totals = np.array([row[2] for row in rows])
    mean = totals.mean(axis=0)
    print(f"[INFO] {len(rows)} frame(s) -> {args.out}")
    print(f"[INFO] <P>   = [{mean[0]: .6e} {mean[1]: .6e} {mean[2]: .6e}] e Angstrom")
    print(f"[INFO] <P>/N = [{mean[0] / n_sites: .6e} {mean[1] / n_sites: .6e} "
          f"{mean[2] / n_sites: .6e}] e Angstrom per site")
    areal = areal_pC_per_m(mean, lattice)
    print(f"[INFO] <P>   = [{areal[0]: .6e} {areal[1]: .6e} {areal[2]: .6e}] pC/m")
    print(f"[INFO] rms fluctuation |P - <P>| = "
          f"{float(np.sqrt(((totals - mean) ** 2).sum(axis=1).mean())): .6e} e Angstrom")


# ----------------------------------------------------------------------
# Self-test
# ----------------------------------------------------------------------
def _triangular_lattice(n1: int, n2: int, a: float = 3.9793, c: float = 20.0):
    """Same n1 x n2 supercell topocharge.py tests on, a1 along x."""
    lattice = np.array([[a * n1, 0.0, 0.0],
                        [-0.5 * a * n2, np.sqrt(3.0) / 2.0 * a * n2, 0.0],
                        [0.0, 0.0, c]])
    i, j = np.meshgrid(np.arange(n1), np.arange(n2), indexing="ij")
    frac = np.stack([i.ravel() / n1, j.ravel() / n2, np.zeros(n1 * n2)], axis=1)
    return frac @ lattice, lattice


def _helix(positions, lattice, h, k, e1, e2):
    """Circular spiral with Q = h B1 + k B2 of the supercell, plane (e1, e2).

    Its bond chirality S_i x S_j = sin(Q.d) (e1 x e2) does not depend on
    position, which is what makes the closed form below exact.
    """
    frac = positions @ np.linalg.inv(lattice)
    phase = 2.0 * np.pi * (h * frac[:, 0] + k * frac[:, 1])
    return (np.cos(phase)[:, None] * np.asarray(e1, float)
            + np.sin(phase)[:, None] * np.asarray(e2, float))


def _orthonormal_plane(normal):
    """An (e1, e2) pair spanning the plane normal to `normal`, with e1 x e2 = normal."""
    normal = np.asarray(normal, float) / np.linalg.norm(normal)
    seed = np.array([1.0, 0.0, 0.0]) if abs(normal[0]) < 0.9 else np.array([0.0, 1.0, 0.0])
    e1 = np.cross(normal, seed)
    e1 /= np.linalg.norm(e1)
    return e1, np.cross(normal, e1)


def _cross_matrix(d):
    """[d]_x, the matrix with [d]_x C = d x C."""
    dx, dy, dz = d
    return np.array([[0.0, -dz, dy], [dz, 0.0, -dx], [-dy, dx, 0.0]])


def _knb_reference():
    """The isotropic spin-current form P_ij = e_ij x (S_i x S_j), for the bond along x.

    Symmetry-allowed, so the generator accepts it, and its orbit is known in
    closed form -- which makes it the one case where every generated matrix can
    be checked against an independent expression rather than against itself.
    """
    return {shell: _cross_matrix(np.array([1.0, 0.0, 0.0])) for shell in SHELL_STEP}


def _helix_closed_form(families_per_layer, n1, n2, h, k, e1, e2, spin_length=1.0):
    """P predicted analytically for the helix above, summed over all layers."""
    normal = np.cross(e1, e2)
    total = np.zeros(3)
    for families in families_per_layer:
        for family in families:
            p, q = family.offset
            q_dot_d = 2.0 * np.pi * (h * p / n1 + k * q / n2)
            total += len(family.site_i) * np.sin(q_dot_d) * (family.matrix @ normal)
    return M_UNIT * spin_length ** 2 * total


def _selftest() -> int:
    rng = np.random.default_rng(0)
    failures = 0

    def check(name, ok, detail):
        nonlocal failures
        print(f"[{'PASS' if ok else 'FAIL'}] {name}: {detail}")
        failures += 0 if ok else 1

    def agrees(got, want, scale):
        """Equal to within double-precision accumulation over the whole lattice.

        The tolerance is relative to the size of the answer rather than
        absolute: P grows with the site count, so an absolute bound that passes
        on one supercell fails on a larger one for no reason.
        """
        return float(np.max(np.abs(np.asarray(got) - np.asarray(want)))) < 1e-12 * scale

    # -- symmetry of the input ------------------------------------------------
    for shell, reference in M_REFERENCE.items():
        zeros = [reference[0, 1], reference[0, 2], reference[1, 0], reference[2, 0]]
        check(f"M^{shell} has the C2x shape", np.allclose(zeros, 0.0),
              f"off-axis entries {zeros}")
        check(f"M^{shell} is C2x invariant",
              np.allclose(transform(C2X, reference), reference, atol=1e-12),
              "x is a twofold axis, so P-3m1 and not P-31m")
        check(f"M^{shell} would fail in the other setting",
              not np.allclose(transform(np.diag([1.0, -1.0, 1.0]), reference), reference),
              "a mirror through x would force M[0][0] = 0; it is "
              f"{reference[0, 0]:g}")

    orbit1 = direction_matrices(M_REFERENCE[1])
    check("orbit has six directions", sorted(orbit1) == [0, 60, 120, 180, 240, 300],
          f"angles {sorted(orbit1)}")

    covariant = all(
        np.allclose(orbit1[int(round(_angle_of(R @ np.array([np.cos(np.radians(ang)),
                                                             np.sin(np.radians(ang)), 0.0])))) % 360],
                    transform(R, M), atol=1e-9)
        for R in d3d_operations() for ang, M in orbit1.items()
    )
    check("orbit is D3d covariant", covariant,
          "M(R d) = det(R) R M(d) R^T holds on all 12 x 6 pairs")

    check("antisymmetry falls out of inversion",
          all(np.allclose(orbit1[(ang + 180) % 360], -orbit1[ang], atol=1e-9)
              for ang in (0, 60, 120)),
          "M(-d) = -M(d) was never imposed by hand")

    # The 60 degree direction is the one R_z cannot reach, and substituting it
    # into the rotation formula corrupts exactly two entries.
    naive = transform(rotation_z(60.0), M_REFERENCE[1])
    check("60 deg is not a naive R_z(60) rotation",
          not np.allclose(naive, orbit1[60]) and np.allclose(
              -transform(rotation_z(240.0), M_REFERENCE[1]), orbit1[60], atol=1e-9),
          f"naive form differs by {float(np.max(np.abs(naive - orbit1[60]))):.1f} "
          "in M[0][2]/M[2][0]")

    root3 = np.sqrt(3.0)
    expected120 = np.array([[169 / 2, 49 * root3 / 2, -139 * root3 / 2],
                            [49 * root3 / 2, 71 / 2, -139 / 2],
                            [2 * root3, 2.0, 5.0]])
    check("M^1(120 deg) matches the closed form",
          np.allclose(orbit1[120], expected120, atol=1e-9),
          "R_z(120) M R_z(120)^T as tabulated")

    # -- the polarization on a lattice ----------------------------------------
    for n1, n2 in ((24, 24), (30, 18)):
        positions, lattice = _triangular_lattice(n1, n2)
        families = build_families(*positions.T, lattice, single_layer=True)
        n_sites = n1 * n2
        n_families = len(DEFAULT_SHELLS) * len(_FAMILY_OFFSETS)
        check(f"family count {n1}x{n2}", len(families[0]) == n_families,
              f"{len(families[0])} families, {n_families} expected")
        check(f"every site bonded once per family {n1}x{n2}",
              all(len(np.unique(f.site_i)) == n_sites and len(np.unique(f.site_j)) == n_sites
                  for f in families[0]),
              "no site is missed or repeated")
        check(f"no self-bond {n1}x{n2}",
              all(not np.any(f.site_i == f.site_j) for f in families[0]),
              "every bond joins two distinct sites")

        # Collinear textures have no bond chirality at all, whatever the sign
        # pattern, so they must give exactly zero.
        axis = _unit(rng.normal(size=(1, 3)))[0]
        for name, m in (("ferromagnet", np.tile(axis, (n_sites, 1))),
                        ("random collinear",
                         rng.choice([-1.0, 1.0], size=n_sites)[:, None] * axis)):
            p = layer_polarization(m, families)
            check(f"{name} gives zero P {n1}x{n2}",
                  np.allclose(p, 0.0, atol=1e-18), f"|P| = {float(np.linalg.norm(p)):.3e}")

        # A circular helix: compare against the closed form, and check that the
        # per-site density it produces is uniform, which it must be because the
        # bond chirality does not depend on position.
        basis = np.linalg.qr(rng.normal(size=(3, 3)))[0]
        e1, e2 = basis[0], basis[1]
        h, k = 3, -2
        m = _helix(positions, lattice, h, k, e1, e2)
        p = layer_polarization(m, families)[0]
        predicted = _helix_closed_form(families, n1, n2, h, k, e1, e2)
        check(f"helix matches the closed form {n1}x{n2}",
              np.allclose(p, predicted, atol=1e-14, rtol=1e-10),
              f"P = {np.array2string(p, precision=6)}")

        p_site = site_polarization(m, families, n_sites)
        check(f"helix sums over sites to P {n1}x{n2}",
              agrees(p_site.sum(axis=0), p, float(np.linalg.norm(p))),
              "sum_i p_i = P")
        spread = float(np.max(np.abs(p_site - p_site.mean(axis=0))))
        check(f"helix density is uniform {n1}x{n2}",
              spread < 1e-12 * float(np.max(np.abs(p_site))),
              f"max deviation from the mean {spread:.2e}")

        # Reversing the helix reverses P, which is the whole reason a static
        # field can select one handedness.
        p_reversed = layer_polarization(_helix(positions, lattice, -h, -k, e1, e2),
                                        families)[0]
        check(f"reversing Q reverses P {n1}x{n2}",
              agrees(p_reversed, -p, float(np.linalg.norm(p))),
              f"|P(-Q) + P(Q)| = {float(np.linalg.norm(p_reversed + p)):.3e}")

        check(f"P scales as S^2 {n1}x{n2}",
              np.allclose(layer_polarization(m, families, spin_length=2.0)[0], 4.0 * p,
                          rtol=1e-12),
              "S = 2 gives four times the S = 1 answer")

    # -- the isotropic limit, where the answer is known independently --------
    positions, lattice = _triangular_lattice(24, 24)
    knb = build_families(*positions.T, lattice, single_layer=True, reference=_knb_reference())
    worst = max(
        float(np.max(np.abs(f.matrix - _cross_matrix(
            [np.cos(np.radians(f.angle)), np.sin(np.radians(f.angle)), 0.0]))))
        for f in knb[0]
    )
    check("KNB orbit reproduces [d]_x on every bond", worst < 1e-12,
          f"max deviation {worst:.2e}, the 60 deg branch included")

    # P ~ Q x n for the isotropic coupling, so a proper screw cannot polarize it.
    # The generalized matrices can, and that gap is the whole point of using them.
    h, k = 3, 0
    reciprocal = reciprocal_lattice_from_real(lattice)
    q_vector = h * reciprocal[0] + k * reciprocal[1]
    screw = _helix(positions, lattice, h, k, *_orthonormal_plane(q_vector))
    cycloid = _helix(positions, lattice, h, k, *_orthonormal_plane([0.0, 0.0, 1.0]))
    full = build_families(*positions.T, lattice, single_layer=True)
    p_screw_knb = layer_polarization(screw, knb)[0]
    p_cycloid_knb = layer_polarization(cycloid, knb)[0]
    p_screw_full = layer_polarization(screw, full)[0]
    check("proper screw does not polarize the isotropic coupling",
          agrees(p_screw_knb, 0.0, float(np.linalg.norm(p_cycloid_knb))),
          f"|P_screw| = {float(np.linalg.norm(p_screw_knb)):.2e} against "
          f"|P_cycloid| = {float(np.linalg.norm(p_cycloid_knb)):.3e}")
    check("proper screw does polarize the anisotropic coupling",
          float(np.linalg.norm(p_screw_full)) > 1e-3,
          f"|P| = {float(np.linalg.norm(p_screw_full)):.3e} e Angstrom, carried entirely "
          "by the off-diagonal entries the isotropic form lacks")

    # -- the strongest test: covariance of the whole path ---------------------
    positions, lattice = _triangular_lattice(12, 12)
    families = build_families(*positions.T, lattice, single_layer=True)
    basis = np.linalg.qr(rng.normal(size=(3, 3)))[0]
    m = _helix(positions, lattice, 2, 1, basis[0], basis[1])
    p = layer_polarization(m, families)[0]
    worst = 0.0
    for rotation in d3d_operations():
        rotated_positions = positions @ rotation.T
        rotated_lattice = lattice @ rotation.T
        # Spins are axial, so they pick up the determinant; P is polar and does not.
        rotated_m = float(np.linalg.det(rotation)) * (m @ rotation.T)
        rotated_families = build_families(*rotated_positions.T, rotated_lattice,
                                          single_layer=True)
        got = layer_polarization(rotated_m, rotated_families)[0]
        worst = max(worst, float(np.max(np.abs(got - rotation @ p))))
    check("P is D3d covariant end to end", worst < 1e-12 * float(np.linalg.norm(p)),
          f"max |P(gS on g-lattice) - R_g P| = {worst:.2e} against |P| = "
          f"{float(np.linalg.norm(p)):.3e}, over all 12 operations")

    # -- guards ---------------------------------------------------------------
    positions, lattice = _triangular_lattice(4, 4)
    try:
        build_families(*positions.T, lattice, single_layer=True, shells=(3,))
        check("shell 3 rejects a 4x4 grid", False, "no error raised")
    except ValueError as exc:
        check("shell 3 rejects a 4x4 grid", "counted twice" in str(exc),
              "a bond two cells long wraps onto its own reverse")
    check("shell 1 accepts a 4x4 grid",
          len(build_families(*positions.T, lattice, single_layer=True, shells=(1,))[0]) == 3,
          "the one-cell bond is still unambiguous there")

    rotated30 = lattice @ rotation_z(30.0).T
    try:
        build_families(*(positions @ rotation_z(30.0).T).T, rotated30, single_layer=True)
        check("a 30 deg lattice is rejected", False, "no error raised")
    except ValueError as exc:
        check("a 30 deg lattice is rejected", "not in the D3d orbit" in str(exc),
              "the P-31m setting cannot be mistaken for P-3m1")

    try:
        build_families(*positions.T, lattice, single_layer=True, shells=(2,))
        check("shell 2 is refused", False, "no error raised")
    except ValueError as exc:
        check("shell 2 is refused", "four-state mapping" in str(exc),
              "it points along the mirrors and needs its own matrix")

    # -- bilayer --------------------------------------------------------------
    positions, lattice = _triangular_lattice(12, 12)
    bilayer = np.concatenate([positions, positions + [0.0, 0.0, 6.0]], axis=0)
    basis = np.linalg.qr(rng.normal(size=(3, 3)))[0]
    top = _helix(positions, lattice, 2, 1, basis[0], basis[1])
    bottom = _helix(positions, lattice, -2, -1, basis[0], basis[1])
    families = build_families(*bilayer.T, lattice, single_layer=False)
    check("bilayer splits into two layers", len(families) == 2, f"{len(families)} layer(s)")
    check("no bond crosses the layers",
          all(np.all((f.site_i < 144) == (f.site_j < 144))
              for layer in families for f in layer),
          "each layer is bonded only to itself")
    p = layer_polarization(np.concatenate([top, bottom]), families)
    check("opposite helices cancel between layers",
          agrees(p.sum(axis=0), 0.0, float(np.linalg.norm(p[0])))
          and float(np.linalg.norm(p[0])) > 1e-6,
          f"|P_total| = {float(np.linalg.norm(p.sum(axis=0))):.3e}, "
          f"|P_layer| = {float(np.linalg.norm(p[0])):.3e}")

    print("\nAll checks passed." if failures == 0 else f"\n{failures} check(s) failed.")
    return failures


if __name__ == "__main__":
    if len(sys.argv) > 1:
        main()
    else:
        raise SystemExit(_selftest())
